### ISSUE TITLE
zero tests found

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/TestItemRunner2.jl#11]
I' m trying to use it for parallel process test running. It always shows
```
0 tests ran, 0 passed, 0 failed, 0 timed out.
```
I' ve tried various paths.

**Comment by xgdgsc** [comment]
ReTest.jl  works.

**Comment by davidanthoff** [comment]
Can you provide a bit more info? What is the exact command you are running? Do these tests show up in VS Code? Is there a particular project you are trying to test that I could try to look at?

**Comment by xgdgsc** [comment]
I came from a discourse post. Does it have to be inside VSCode? I was trying outside.

**Comment by davidanthoff** [comment]
Can you link to the post? This is just way too little information for me to help in any way... You must have typed some code to run this, can you just copy-paste that code here?

> Does it have to be inside VSCode? I was trying outside.

No, I'm just wondering whether VS Code is finding these tests if you open the same folder in VS Code.

**Comment by xgdgsc** [comment]
From https://discourse.julialang.org/t/multi-threaded-testing/95372/3?u=xgdgsc . I just ran 
```
using TestItemRunner2
run_tests(pwd())
```
They don' t appear in vscode either, `Pkg.test` works.

**Comment by davidanthoff** [comment]
You are using the `@testitem` macro?

**Comment by xgdgsc** [comment]
No. Didn' t know about that.
